---
title: "IDA Gossip Experiment Results"
author: "Kadir Korkmaz"
date: "7/22/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

```{r first_chunk_delivery, echo=FALSE}
library(ggplot2)
library(dplyr)


mb_to_bytes<-1048576

#folder_path <- "/home/kadir/Desktop/ida-experiments-nomal-case/"

folder_path <- "/home/kadir/Desktop/ida-gossip/scripts/stats/connection_count/"

target_variable <- as.name("ConnectionCount")
x_label="Message Size, MB"

df_chunks <- read.csv(paste(folder_path, "first_chunk_delivery_df.tsv", sep = ""), sep = "\t", header = TRUE)
df_chunks$MessageSize = df_chunks$MessageSize / mb_to_bytes


df_chunks <- df_chunks %>% filter(MessageChunkCount>=16 )

#df_chunks_classic <- df_chunks %>% filter(MessageChunkCount==1)

p1 <- ggplot(df_chunks, aes(x= as.factor(!!target_variable), y=Median, group=MessageChunkCount, color=as.factor(MessageChunkCount))) +
      geom_line()+
      geom_point()+
      labs(x=x_label, y="First Chunk Delivery Time(ms)",  color='Chunk Count') +
      expand_limits(y = 0) + 
      theme(legend.position="top")



```


```{r message_delivery, echo=FALSE}

df_message_delivery <- read.csv(paste(folder_path, "message_received_df.tsv", sep = ""), sep = "\t", header = TRUE)
df_message_delivery$MessageSize = df_message_delivery$MessageSize / mb_to_bytes

df_message_delivery <- df_message_delivery %>% filter(MessageChunkCount>=16)

p2 <- ggplot(df_message_delivery, aes(x= as.factor(!!target_variable), y=Median, group=MessageChunkCount, color=as.factor(MessageChunkCount) )) +
      geom_line()+
      geom_point()+
      labs(x=x_label, y="Message Delivery Time(ms)",  color='Chunk Count') +
      expand_limits(y = 0) +
      theme(legend.position="top")


```

```{r queue_length, echo=FALSE, fig.height=3}

df_network_usage <- read.csv(paste(folder_path, "network_usage_df.tsv", sep = ""), sep = "\t", header = TRUE)
df_network_usage$MessageSize = df_network_usage$MessageSize / mb_to_bytes
df_network_usage$Median = df_network_usage$Median / mb_to_bytes

df_network_usage <- df_network_usage %>% filter(MessageChunkCount>=16)

p3 <- ggplot(df_network_usage, aes(x= as.factor(!!target_variable), y=Median, group=MessageChunkCount, color=as.factor(MessageChunkCount) )) +
      geom_line()+
      geom_point()+
      labs(x=x_label, y="Network Usage(MB)",  color='Chunk Count') +
      expand_limits(y = 0) +
      guides(color = FALSE)


```



```{r allign_plots, echo=FALSE, fig.height=9, fig.width=8}

library(gridExtra)

#p1 <- p1 + theme(axis.title.x = element_blank())
#p2 <- p2 + theme(axis.title.x = element_blank())
#p3 <- p3 + theme(axis.title.x = element_blank())

plots <- list( p1, p2, p3 )
grobs <- list()
widths <- list()

for (i in 1:length(plots)){
    grobs[[i]] <- ggplotGrob(plots[[i]])
    widths[[i]] <- grobs[[i]]$widths[2:5]
}

maxwidth <- do.call(grid::unit.pmax, widths)

for (i in 1:length(grobs)){
     grobs[[i]]$widths[2:5] <- as.list(maxwidth)
}

do.call( "grid.arrange", c(grobs, ncol = 1) )

```


\newpage
```{r, echo=FALSE}
suppressPackageStartupMessages(library(dplyr))
library(knitr)

names(df_chunks)[names(df_chunks) == 'MessageChunkCount'] <- "ChunkCount"
names(df_message_delivery)[names(df_message_delivery) == 'MessageChunkCount'] <- "ChunkCount"
names(df_network_usage)[names(df_network_usage) == 'MessageChunkCount'] <- "ChunkCount"

df_chunks <- df_chunks %>% select( !!target_variable, ChunkCount, Min, FirstQuartile, Median, ThirdQuartile, Max, Mean, RowCount) %>% arrange( !!target_variable, ChunkCount )
kable(df_chunks, caption = "First Chunk Delivery Time(ms)")

```

\newpage
```{r, echo=FALSE}

df_message_delivery <- df_message_delivery  %>% select( !!target_variable, ChunkCount,  Min, FirstQuartile, Median, ThirdQuartile, Max, Mean, RowCount) %>% arrange( !!target_variable, ChunkCount )
kable(df_message_delivery, caption = "Message Delivery Time(ms)")

```


\newpage

```{r, echo=FALSE}

df_network_usage$Min = df_network_usage$Min / mb_to_bytes
df_network_usage$FirstQuartile = df_network_usage$FirstQuartile / mb_to_bytes
df_network_usage$ThirdQuartile = df_network_usage$ThirdQuartile / mb_to_bytes
df_network_usage$Max = df_network_usage$Max / mb_to_bytes
df_network_usage$Mean = df_network_usage$Mean / mb_to_bytes



df_network_usage <- df_network_usage  %>% select( !!target_variable, ChunkCount, Min, FirstQuartile, Median, ThirdQuartile, Max, Mean, RowCount) %>% arrange( !!target_variable, ChunkCount )
kable(df_network_usage, caption = "Network Usage(MB)")

```



\newpage
```{r, echo=FALSE, fig.height=6, fig.width=4}

#https://waterdata.usgs.gov/blog/beyond-basic-plotting/

names(df_chunks)[names(df_chunks) == 'MessageChunkCount'] <- "ChunkCount"
names(df_message_delivery)[names(df_message_delivery) == 'MessageChunkCount'] <- "ChunkCount"
names(df_network_usage)[names(df_network_usage) == 'MessageChunkCount'] <- "ChunkCount"

#FirstQuartile ThirdQuartile

df_chunks <- df_chunks %>% select( !!target_variable, ChunkCount, Median,FirstQuartile,ThirdQuartile) %>% rename( ChunkDelivery = Median)
df_message_delivery <- df_message_delivery  %>% select( !!target_variable, ChunkCount, Median,FirstQuartile,ThirdQuartile) %>% rename( MessageDelivery = Median)
df_network_usage <- df_network_usage  %>% select( !!target_variable, ChunkCount, Median,FirstQuartile,ThirdQuartile) %>% rename( NetworkUsage = Median)


library(reshape)

df_chunks.melted <- melt(df_chunks, id=c("ConnectionCount","ChunkCount", "FirstQuartile", "ThirdQuartile"))
df_message_delivery.melted <- melt(df_message_delivery, id=c("ConnectionCount","ChunkCount", "FirstQuartile", "ThirdQuartile"))
df_network_usage.melted <- melt(df_network_usage, id=c("ConnectionCount","ChunkCount", "FirstQuartile", "ThirdQuartile"))
 
merged_df <- rbind( df_chunks.melted, df_message_delivery.melted )
merged_df <- rbind( merged_df, df_network_usage.melted )

p <- ggplot(merged_df, aes(x= as.factor(!!target_variable), y=value,  group=ChunkCount, color=as.factor(ChunkCount), linetype=as.factor(ChunkCount), shape=as.factor(ChunkCount) )) +
      geom_line()+
      geom_point()+
      geom_errorbar( aes(ymin=FirstQuartile, ymax=ThirdQuartile), width=0.1, alpha=1, size=0.2)+
      #expand_limits(y = 0) +
      labs(color='Chunk Count', shape='Chunk Count', linetype='Chunk Count') +
      theme_bw()+
      theme(legend.position="top") +
      ylab(NULL) +
      xlab(x_label) +
      theme(strip.background = element_blank(), # remove the background
          strip.placement = "outside", legend.title=element_text(size=8), legend.margin=margin(0,-0,-6,0))

#, switch = "y"
p <- p + facet_grid(variable ~ ., scales = "free_y" , labeller = as_labeller(
      c(ChunkDelivery = "First Chunk Delivery, ms", MessageDelivery = "Message Delivery, ms", NetworkUsage = "Uploaded Data, MB"))
  ) + theme(plot.margin = margin(0,0,0,0, "cm")) + scale_y_continuous(labels = scales::comma) #+ scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) 

p

ggsave("fault-free.pdf", p)


```


\newpage
```{r, include=FALSE, echo=FALSE, fig.height=6, fig.width=4}

#https://waterdata.usgs.gov/blog/beyond-basic-plotting/
# 
# names(df_chunks)[names(df_chunks) == 'MessageChunkCount'] <- "ChunkCount"
# names(df_message_delivery)[names(df_message_delivery) == 'MessageChunkCount'] <- "ChunkCount"
# names(df_network_usage)[names(df_network_usage) == 'MessageChunkCount'] <- "ChunkCount"
# 
# 
# 
# df_chunks <- df_chunks %>% select( !!target_variable, ChunkCount, Median) %>% rename( ChunkDelivery = Median)
# df_message_delivery <- df_message_delivery  %>% select( !!target_variable, ChunkCount, Median) %>% rename( MessageDelivery = Median)
# df_network_usage <- df_network_usage  %>% select( !!target_variable, ChunkCount, Median) %>% rename( NetworkUsage = Median)
# 
# merged_df <- merge( df_chunks, df_message_delivery )
# merged_df <- merge( merged_df, df_network_usage )
# 
# library(reshape)
# melted_df <- melt(merged_df, id=c("MessageSize","ChunkCount"))
# 
# kable(melted_df)
# 
# p <- ggplot(melted_df, aes(x= as.factor(!!target_variable), y=value,  group=ChunkCount, color=as.factor(ChunkCount), linetype=as.factor(ChunkCount), shape=as.factor(ChunkCount) )) +
#       geom_line()+
#       geom_point()+
#       #expand_limits(y = 0) +
#       labs(color='Chunk Count', shape='Chunk Count', linetype='Chunk Count') +
#       theme_bw()+
#       theme(legend.position="top") +
#       ylab(NULL) +
#       xlab(x_label) +
#       theme(strip.background = element_blank(), # remove the background
#           strip.placement = "outside", legend.title=element_text(size=8), legend.margin=margin(0,-0,-6,0))
# 
# #, switch = "y"
# p <- p + facet_grid(variable ~ ., scales = "free_y" , labeller = as_labeller(
#       c(ChunkDelivery = "First Chunk Delivery, ms", MessageDelivery = "Message Delivery, ms", NetworkUsage = "Uploaded Data, MB"))
#   ) + theme(plot.margin = margin(0,0,0,0, "cm")) #+ scale_y_continuous(labels = function(x) format(x, scientific = TRUE))
# 
# p
# 
# ggsave("fault-free.pdf", p)
# 

```


