---
title: "IDA Gossip Experiment Results"
author: "Kadir Korkmaz"
date: "7/22/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

```{r first_chunk_delivery, echo=FALSE}
library(ggplot2)
library(dplyr)


mb_to_bytes<-1048576


folder_path <- "/home/kadir/Desktop/ida-gossip-experiments/simultaneously_served_conn_2mb/"
target_variable <- as.name("ParallelSendCount")

parallel_send_plot <- TRUE

#folder_path <- "/home/kadir/Desktop/ida-gossip-experiments/normal-case-fault-free-fanout-8/"
#target_variable <- as.name("MessageSize")

x_label="Message Size (MB)"

df_chunks <- read.csv(paste(folder_path, "first_chunk_delivery_df.tsv", sep = ""), sep = "\t", header = TRUE)
df_chunks$MessageSize = df_chunks$MessageSize / mb_to_bytes

```


```{r message_delivery, echo=FALSE}

df_message_delivery <- read.csv(paste(folder_path, "message_received_df.tsv", sep = ""), sep = "\t", header = TRUE)
df_message_delivery$MessageSize = df_message_delivery$MessageSize / mb_to_bytes

```

```{r queue_length, echo=FALSE, fig.height=3}

df_network_usage <- read.csv(paste(folder_path, "network_usage_df.tsv", sep = ""), sep = "\t", header = TRUE)
df_network_usage$MessageSize = df_network_usage$MessageSize / mb_to_bytes
df_network_usage$Median = df_network_usage$Median / mb_to_bytes

```


\newpage
```{r, echo=FALSE}
suppressPackageStartupMessages(library(dplyr))
library(knitr)

names(df_chunks)[names(df_chunks) == 'MessageChunkCount'] <- "ChunkCount"
names(df_message_delivery)[names(df_message_delivery) == 'MessageChunkCount'] <- "ChunkCount"
names(df_network_usage)[names(df_network_usage) == 'MessageChunkCount'] <- "ChunkCount"

df_chunks <- df_chunks %>% select( !!target_variable, ChunkCount, Min, FirstQuartile, Median, ThirdQuartile, Max, Mean, RowCount) %>% arrange( !!target_variable, ChunkCount )



# converts ms to S
df_chunks$FirstQuartile <- df_chunks$FirstQuartile / 1000
df_chunks$Median <- df_chunks$Median / 1000
df_chunks$ThirdQuartile <- df_chunks$ThirdQuartile / 1000


```

\newpage
```{r, echo=FALSE}

df_message_delivery <- df_message_delivery  %>% select( !!target_variable, ChunkCount,  Min, FirstQuartile, Median, ThirdQuartile, Max, Mean, RowCount) %>% arrange( !!target_variable, ChunkCount )

# converts ms to S
df_message_delivery$FirstQuartile <- df_message_delivery$FirstQuartile / 1000
df_message_delivery$Median <- df_message_delivery$Median / 1000
df_message_delivery$ThirdQuartile <- df_message_delivery$ThirdQuartile / 1000

```


\newpage

```{r, echo=FALSE}

df_network_usage$Min = df_network_usage$Min / mb_to_bytes
df_network_usage$FirstQuartile = df_network_usage$FirstQuartile / mb_to_bytes
df_network_usage$ThirdQuartile = df_network_usage$ThirdQuartile / mb_to_bytes
df_network_usage$Max = df_network_usage$Max / mb_to_bytes
df_network_usage$Mean = df_network_usage$Mean / mb_to_bytes



df_network_usage <- df_network_usage  %>% select( !!target_variable, ChunkCount, Min, FirstQuartile, Median, ThirdQuartile, Max, Mean, RowCount) %>% arrange( !!target_variable, ChunkCount )

```



\newpage
```{r, echo=FALSE, fig.width=3.5, fig.height=3, eval=parallel_send_plot}

##### ParallelSendCount  Plots ######

target_variable <- as.name("ParallelSendCount")
x_label="Simultaneously Served Connection Count"

#https://waterdata.usgs.gov/blog/beyond-basic-plotting/

names(df_chunks)[names(df_chunks) == 'MessageChunkCount'] <- "ChunkCount"
names(df_message_delivery)[names(df_message_delivery) == 'MessageChunkCount'] <- "ChunkCount"
names(df_network_usage)[names(df_network_usage) == 'MessageChunkCount'] <- "ChunkCount"

#FirstQuartile ThirdQuartile

df_chunks <- df_chunks %>% select( !!target_variable, ChunkCount, Median,FirstQuartile,ThirdQuartile) %>% rename( ChunkDelivery = Median)
df_message_delivery <- df_message_delivery  %>% select( !!target_variable, ChunkCount, Median,FirstQuartile,ThirdQuartile) %>% rename( MessageDelivery = Median)
df_network_usage <- df_network_usage  %>% select( !!target_variable, ChunkCount, Median,FirstQuartile,ThirdQuartile) %>% rename( NetworkUsage = Median)


library(reshape)

df_chunks.melted <- melt(df_chunks, id=c("ParallelSendCount","ChunkCount", "FirstQuartile", "ThirdQuartile"))
df_message_delivery.melted <- melt(df_message_delivery, id=c("ParallelSendCount","ChunkCount", "FirstQuartile", "ThirdQuartile"))
df_network_usage.melted <- melt(df_network_usage, id=c("ParallelSendCount","ChunkCount", "FirstQuartile", "ThirdQuartile"))
 
merged_df <- rbind( df_chunks.melted, df_message_delivery.melted )
#merged_df <- rbind( merged_df, df_network_usage.melted )

p <- ggplot(merged_df, aes(x= as.factor(!!target_variable), y=value,  group=ChunkCount, color=as.factor(ChunkCount), linetype=as.factor(ChunkCount), shape=as.factor(ChunkCount) )) +
      geom_line()+
      geom_point()+
      geom_errorbar( aes(ymin=FirstQuartile, ymax=ThirdQuartile), width=0.1, alpha=1, size=0.2)+
      expand_limits(y = 0) +
      labs(color='Chunk Count', shape='Chunk Count', linetype='Chunk Count') +
      theme_bw()+
      theme(legend.position="top") +
      ylab(NULL) +
      xlab(x_label) +
      theme(strip.background = element_blank(), # remove the background
          strip.placement = "outside", legend.margin=margin(0,-0,-6,0))

#, switch = "y"
p <- p + facet_grid(variable ~ ., scales = "free_y", switch = "y", labeller = as_labeller(
      c(ChunkDelivery = "First Chunk Latency (S)", MessageDelivery = "Latency (S)" , NetworkUsage = "Uploaded Data (MB)"))
  ) + theme(plot.margin = margin(0,0.5,0,0, "cm")) + scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) #+ scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) 

p <- p + theme(text = element_text(family="Times", face="plain", size=8), strip.text.y=element_text(family="Times", face="plain", size=8))

p

ggsave("simultaneously-served-connections.pdf", p)


```

\newpage
```{r, echo=FALSE, fig.width=3.5, fig.height=4.5, eval=!parallel_send_plot}

#https://waterdata.usgs.gov/blog/beyond-basic-plotting/

names(df_chunks)[names(df_chunks) == 'MessageChunkCount'] <- "ChunkCount"
names(df_message_delivery)[names(df_message_delivery) == 'MessageChunkCount'] <- "ChunkCount"
names(df_network_usage)[names(df_network_usage) == 'MessageChunkCount'] <- "ChunkCount"

#FirstQuartile ThirdQuartile

df_chunks <- df_chunks %>% select( !!target_variable, ChunkCount, Median,FirstQuartile,ThirdQuartile) %>% rename( ChunkDelivery = Median)
df_message_delivery <- df_message_delivery  %>% select( !!target_variable, ChunkCount, Median,FirstQuartile,ThirdQuartile) %>% rename( MessageDelivery = Median)
df_network_usage <- df_network_usage  %>% select( !!target_variable, ChunkCount, Median,FirstQuartile,ThirdQuartile) %>% rename( NetworkUsage = Median)


library(reshape)

df_chunks.melted <- melt(df_chunks, id=c("MessageSize","ChunkCount", "FirstQuartile", "ThirdQuartile"))
df_message_delivery.melted <- melt(df_message_delivery, id=c("MessageSize","ChunkCount", "FirstQuartile", "ThirdQuartile"))
df_network_usage.melted <- melt(df_network_usage, id=c("MessageSize","ChunkCount", "FirstQuartile", "ThirdQuartile"))
 
merged_df <- rbind( df_chunks.melted, df_message_delivery.melted )
merged_df <- rbind( merged_df, df_network_usage.melted )

p <- ggplot(merged_df, aes(x= as.factor(!!target_variable), y=value,  group=ChunkCount, color=as.factor(ChunkCount), linetype=as.factor(ChunkCount), shape=as.factor(ChunkCount) )) +
      geom_line()+
      geom_point()+
      geom_errorbar( aes(ymin=FirstQuartile, ymax=ThirdQuartile), width=0.1, alpha=1, size=0.2)+
      #expand_limits(y = 0) +
      labs(color='Chunk Count', shape='Chunk Count', linetype='Chunk Count') +
      theme_bw()+
      theme(legend.position="top") +
      ylab(NULL) +
      xlab(x_label) +
      theme(strip.background = element_blank(), # remove the background
          strip.placement = "outside", legend.margin=margin(0,-0,-6,0))

#, switch = "y"
p <- p + facet_grid(variable ~ ., scales = "free_y", switch = "y", labeller = as_labeller(
      c(ChunkDelivery = "First Chunk Latency (S)", MessageDelivery = "Latency (S)", NetworkUsage = "Uploaded Data (MB)"))
  ) + theme(plot.margin = margin(0,0.5,0,0, "cm")) + scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) #+ scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) 

p <- p + theme(text = element_text(family="Times", face="plain", size=8), strip.text.y=element_text(family="Times", face="plain", size=8))

p

ggsave("fault-free.pdf", p)


```
