---
# The playbook uploads experiment artifacts to remote machines

- hosts: registry
  tasks:
    - name: killing registery
      shell: 
        cmd: pkill registery || /bin/true

    - name: deploying registery service
      shell: cd ~/ida-gossip; nohup ./registery > registery.log 2>&1 &


- hosts: all
  tasks:
    - name: killing nodes
      shell: 
        cmd: pkill node || /bin/true

    - name: deploying nodes
      shell: cd ~/ida-gossip; ./deploy-nodes.sh 256 "{{ groups['registry'][0] }}:1234" eno1