---
# The playbook download logs from registery machine

- hosts: registry
  any_errors_fatal: true

  tasks:
    - name: Zips stats forlder on registery machine
      community.general.archive:
        path: ~/ida-gossip/stats
        dest: ~/stats.zip
        format: zip
        remove: yes

    - name: Donwloads stats.zip to the Desktop
      fetch:
        src: /root/stats.zip
        dest: "{{ dest }}"
        flat: yes
