---
# The playbook install dependencies

- hosts: all
  tasks:
    - name: Install cgroup-tools (state=present is optional)
      apt:
        name: cgroup-tools
        state: present

    - name: Install iproute (state=present is optional)
      apt:
        name: iproute2
        state: present

    - name: modify nofile soft limit for the user root
      community.general.pam_limits:
        domain: root
        limit_type: soft
        limit_item: nofile
        value: 102400