---
# The playbook uploads experiment artifacts to remote machines

- hosts: all
  any_errors_fatal: true
  gather_facts: False
  
  tasks:
    - name: remove artifacts from the server
      file:
        path: ~/ida-gossip
        state: absent

    - name: copy artifacts to the remote server
      copy:
        src: ../artifacts/
        dest: ~/ida-gossip
        mode: preserve