---
# The playbook uploads experiment artifacts to remote machines

- hosts: registry
  any_errors_fatal: true
  gather_facts: False

  tasks:
    - name: copy artifacts to the remote server
      copy:
        src: ../artifacts/config.json
        dest: ~/ida-gossip/config.json
        mode: preserve